linux-desktop-devops.yml: Add uidmap
newuidmap is required to fix the following problem

  ❯ podman pull wordpress
  Error: command required for rootless mode with multiple IDs: exec: "newuidmap": executable file not found in $PATH